title: Preity Rashmi
logo: /assets/img/logo.png
description: Senior Software Developer | <a href="https://www.linkedin.com/in/preity-rashmi/"> LinkedIn </a> 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
